# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.8

before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc

install:
  - pipenv install --dev --ignore-pipfile --deploy

before_script: # code coverage tool
   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
   - chmod +x ./cc-test-reporter
   - ./cc-test-reporter before-build
script:
  - pytest --cov-report xml --cov-report term
  - make -C docsrc html
  - cp -a docsrc/_build/html/. docs
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
- provider: pages:git
  skip_cleanup: true
  on:
    branch: master
  verbose: true
  token: $GITHUB_TOKEN
  edge: true
  local_dir: ./docs
  keep_history: true
- provider: script
  skip_cleanup: true
  on:
    branch: master
  script: pipenv run python -m submission
