# Config file for automatic testing at travis-ci.org
env:
  global:
    - CANVAS_URL=https://canvas.harvard.edu/
language: python
python:
  - 3.8

before_script:
   - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
   - pipenv install --dev --ignore-pipfile --deploy

script:
  - skip

stages:
  - build
jobs:
  include:
    - stage: build
      name: Deploy to GitHub Pages
      script:
        - cp -a docsrc/_build/html/. docs
      deploy:
        provider: pages:git
        verbose: true
        token: "$CI_USER_TOKEN"
        edge: true
        local_dir: ./docs/build/html/
        keep_history: true
        on:
          branch: master
